### ISSUE TITLE
Bug: More than one energy cards can be assigned to the active pokemon in one turn

### ISSUE THREAD

**Issue by satgur** [h0111in/PokemonGoBack#40] opened 2017-06-22 21:57 UTC

**Comment by h0111in** [comment] 2017-06-23 14:41
The issues is fixed in latest update please check it again.
if it is fixed, please close the issue.

**Comment by z-mehta** [comment] 2017-06-23 17:40
the issue is fixed.......pllz @satgur  close the issue

**Closed as completed** 2017-06-23 19:00 UTC
